FROM node:20-alpine

WORKDIR /app

RUN npm install -g live-server

COPY index.html .
COPY css/ css/
COPY js/ js/
COPY samples/ samples/

EXPOSE 3000

CMD ["live-server", "--port=3000", "--host=0.0.0.0", "--no-browser"]
